[project]
name = "app-studio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.84.0",
    "psycopg2-binary>=2.9.10",
    "python-dotenv>=1.1.0",
    "reflex==0.7.14",
    "reflex-local-auth>=0.3.0",
]
